# Generated by Django 4.2.1 on 2023-05-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_applicant_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='pic',
        ),
        migrations.AddField(
            model_name='applicant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='applicant_pics/covers'),
        ),
    ]
